alias k="kubectl"
alias kcf="kubectl create -f"
alias kg="kubectl get"
alias kgp="kubectl get pods"
alias ks="kubectl -n kube-system"
alias ksg="kubectl -n kube-system get"
alias ksgp="kubectl -n kube-system get pods"
